### ISSUE TITLE
Send an alert on error

### ISSUE THREAD

**Issue by ASaiAnudeep** [test-results-reporter/testbeats#169]
We need a new `error` condition - https://test-results-reporter.github.io/guides/conditions.html

```json
{
  "targets": [
    {
      "name": "teams",
      "condition": "pass",
      "inputs": {
        "url": "<teams-success-channel-incoming-webhook-url>"
      }
    },
     {
      "name": "teams",
       "condition": "error",
      "inputs": {
        "url": "<teams-error-channel-incoming-webhook-url>"
      }
    }
  ],
  "results": [
    {
      "type": "testng",
      "files": ["path/to/testng-results.xml"]
    }
  ]
}
```

we can also support a new input to handler errors.

```json
{
  "targets": [
    {
      "name": "teams",
      "condition": "pass",
      "error_report": true,
      "inputs": {
        "url": "<teams-success-channel-incoming-webhook-url>",
        "error_report": true,
      }
    }
  ],
  "results": [
    {
      "type": "testng",
      "files": ["path/to/testng-results.xml"]
    }
  ]
}
```

**Comment by leelaprasadv** [comment]
@ASaiAnudeep how will it be different from failure? Is this for error during the reporting?

**Comment by ASaiAnudeep** [comment]
This focuses on errors that we encounter while parsing the results or doing any other kind of operation. So we a generic alert to the given target mentioning - `something went wrong while reporting results`. The teams would be proactive notified about issues.

**Comment by ASaiAnudeep** [comment]
this is duplicate of - https://github.com/test-results-reporter/testbeats/issues/51
