### ISSUE TITLE
Slack notification preview problem.

### ISSUE THREAD

**Issue by ASaiAnudeep** [test-results-reporter/testbeats#179]
### Discussed in https://github.com/test-results-reporter/testbeats/discussions/125

<div type='discussions-op-text'>

<sup>Originally posted by **kartal-huseyin** March 28, 2023</sup>
Since our report includes just inputs as an attachment. I think we requrie to send a text with the report. How to put a text in to report.

![image](https://user-images.githubusercontent.com/98432117/228186281-b845f354-e95b-4727-9e5d-2aa4db8e1ebf.png)

</div>

**Comment by mnoorenberghe** [comment]
Yes, I have the same issue, please include something like `Results: 26 / 38 Passed (68%)` in the fallback.
