### ISSUE TITLE
Environment Label

### ISSUE THREAD

**Issue by ASaiAnudeep** [test-results-reporter/testbeats#190]
```json
{
  "environment": "Production"
  "targets": []
  "results": []
}
```

This should append `environment` to title of the test run and run name for portal

```
Smoke Test - Production
```

**Comment by leelaprasadv** [comment]
@ASaiAnudeep - We can handle it via ENV vars in the title is it not? 

```json
{
"title" : "Smoke Test - {ENVIRONMENT}"
}
```

Using this pattern there will be no need to maintain hardcoded configuration in the file and single file will work for multiple env (DEV, QA, PROD etc)
