### ISSUE TITLE
Publishing to slack channel fails after update to v2.0.3

### ISSUE THREAD

**Issue by otenta** [test-results-reporter/testbeats#192]
Hello everyone, i recently updated from test reporter to test beats keeping the same config files etc.
Everything worked fine until the update from v2.0.2 to v2.0.3. When the update happened, my gitlab CI stage for publishing the results failed.

in my script i have
`npm install -g testbeats@latest`
`testbeats publish -c testbeats.config.json`
where my config.json is
`{ "targets": [ { "name": "slack", "inputs": { "url": "https://hooks.slack.com/services/{SLACK_TOKEN}", "publish": "test-summary", "title": " Test Results * \n *- Branch:* {CI_COMMIT_REF_NAME} *-* \n *- Commit:* {CI_COMMIT_SHORT_SHA} *-" }, "extensions": [ { "name": "hyperlinks", "inputs": { "links": [ { "text": "Pipeline", "url": "{CI_PIPELINE_URL}" }, { "text": "Report Portal", "url": "{Report_portal_url}" } ] } }, { "name": "report-portal-analysis", "inputs": { "url": "{REPORT_PORTAL_BASE_URL}", "api_key": "{REPORT_PORTAL_TOKEN}", "project": "myproject", "launch_name": "my project test" } }, { "name": "quick-chart-test-summary" } ] } ], "results": [ { "type": "junit", "files": [ "{MODIFIED_XML_PATH}" ] } ] }`
Now i get this error
`🥁 TestBeats v2.0.3 Report publish failed: Config file not found: /builds/services/smth/smth2/myproject/devops/testbeats.config.json`
Which is bizarre because in my bash script i pwd to check the working directory and cd to devops and ls and see the config there.

**Comment by otenta** [comment]
Hello @ASaiAnudeep, does this PR fix the issue? When will it be available? Thanks for your effort!

**Comment by ASaiAnudeep** [comment]
@otenta release new version. can you share the new logs here.

**Comment by otenta** [comment]
@ASaiAnudeep the issue has been solved! It was an error caused by the format of the testbeats config. It couldn't parse the target name properly
