### ISSUE TITLE
google chat report isn't being called after a success cypress run headless

### ISSUE THREAD

**Issue by PatryckFlores98** [test-results-reporter/testbeats#232]
google chat report isn't being called after a success cypress run headless

After a failing run, the report is correctly sent to google chat.

Currently using cypress-mochawesome-reporter and testbeats latest version with cypress 13.13.0

**Comment by ASaiAnudeep** [comment]
Hello @PatryckFlores98 , can you share us more details on the error messages you see while running the cli command?

**Comment by ASaiAnudeep** [comment]
Closing this issue. Please open if the issue still exists.
