### ISSUE TITLE
Gitlab - branch hyperlink 

### ISSUE THREAD

**Issue by amrmahmoud11** [test-results-reporter/testbeats#260]
It seems that the branch hyperlink is taking me to a 404 on gitlab, the url is missing:  `/-/tree/`
Correct url:
`https://<gitlab-domain>/<namespace>/<project-name>/-/tree/<branch-name>`

What it links to which results in a 404:
`https://<gitlab-domain>/<namespace>/<project-name><branch-name>`

Here is my testbeats.config.json:
```
{
    "targets": [
      {
        "name": "teams",
        "inputs": {
          "url": "{MS_TEAMS_WEBHOOK_URL}",
          "title": "Playwright Automation - E2E Tests",
          "publish": "test-summary"
        }
      }
    ],
    "extensions": [
      {
        "name": "quick-chart-test-summary"
      },
      {
        "name": "ci-info",
        "inputs": {
          "show_repository": true,
          "show_repository_branch": true,
          "show_build": true,
          "data": [
            {
              "key": "Download Report",
              "value": "{CI_PROJECT_URL}/-/jobs/{CI_JOB_ID}/artifacts/download",
              "type": "hyperlink"
            }
          ]
        }
      }
    ],
    "results": [
      {
        "type": "junit",
        "files": ["results.xml"]
      }
    ]
  }
```

Here is the result:
![Screenshot 2024-12-10 201850](https://github.com/user-attachments/assets/cf8156a6-25e5-4c70-849a-120fabdde80a)

Anyway to remove the hyperlink and only have the branch name as a workaround if this is indeed a bug?

**Comment by leelaprasadv** [comment]
@amrmahmoud11 Thanks for reporting it. 
Could you please share the details of below env vars from the CI ?

CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
CI_COMMIT_REF_NAME

**Comment by amrmahmoud11** [comment]
`CI_COMMIT_REF_NAME=TeamsNotificationReport`
It seems in gitlab this env var `CI_MERGE_REQUEST_SOURCE_BRANCH_NAME`  is not there, I also checked by listing all the env variables on the CI to look for it.
The only other env var that contained any information about the branch was :
`CI_COMMIT_BRANCH=TeamsNotificationReport`

**Comment by ASaiAnudeep** [comment]
In GitHub repository branch name is usually prefixed with `refs/heads`.
Need to fix this for GitLab - https://github.com/test-results-reporter/testbeats/blob/main/src/extensions/ci-info.extension.js#L90

**Comment by leelaprasadv** [comment]
@amrmahmoud11 Yeah, this helps. We will roll out a fix for this in next release this weekend.
