### ISSUE TITLE
Global Extensions

### ISSUE THREAD

**Issue by ASaiAnudeep** [test-results-reporter/testbeats#62]
Global extensions will help to share common extensions across targets.

```json
{
  "targets": [],
  "extensions": [],
  "results": []
}
```

```sh
# create a new issue for supporting this
Support new option to either append or override the extension.
- **mode**: "append/override"
```

**Comment by leelaprasadv** [comment]
@ASaiAnudeep do we want to support global extensions in addition to extensions at target level? Or is it a complete change that only supports global extensions going forward?

**Comment by ASaiAnudeep** [comment]
Yes, we want to support global extensions in addition to extensions at target level. Global extensions run first and then target level extentensions.
